# Generated by Django 4.1.7 on 2023-03-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Input author's name", max_length=100, verbose_name="Author's name")),
                ('last_name', models.CharField(help_text=" Input author's last name", max_length=100, verbose_name="Author's last name")),
                ('date_of_birth', models.DateField(blank=True, help_text='Input date of birth', null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Input date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Input title', max_length=200, verbose_name='Title')),
                ('summary', models.TextField(help_text='Input the book description', max_length=1000, verbose_name='Annotation')),
                ('isbn', models.CharField(help_text='Should be 13 symbols', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Choose the author', null=True, to='catalog.author', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Input book genre', max_length=200, verbose_name='Book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Input book language', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input book status', max_length=20, verbose_name='Book status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Input the inventory number of the book', max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Input publisher and year of release', max_length=200, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Input the end date of the status', null=True, verbose_name='End status date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change condition of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose the genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose the language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Language'),
        ),
    ]
