# Generated by Django 4.0.4 on 2022-04-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Input the author's first name", max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(help_text="Input the author's last name", max_length=100, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, help_text="Input the author's birthdate", null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text="Input the author's date of death", null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Input the name of the book', max_length=200, verbose_name='Name of the book')),
                ('summary', models.TextField(help_text='Input a short description of the book', max_length=1000, verbose_name='Book annotation')),
                ('isbn', models.CharField(help_text='No longer than 13 symbols', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Choose the author of the book', null=True, to='catalog.author', verbose_name='Author of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input the genre of the book', max_length=200, verbose_name='The book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input the language of the book', max_length=20, verbose_name='The language of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input the status of the book instance', max_length=20, verbose_name='The book instance status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Input the inventory number of the book', max_length=20, null=True, verbose_name='The inventory number')),
                ('imprint', models.CharField(help_text='Input the publishing house and the year of the release', max_length=200, verbose_name='The publishing house')),
                ('due_back', models.DateField(blank=True, help_text='Input the date of the status ending', null=True, verbose_name='The date of the status ending')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change the condition of the book instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='The status of the book instance')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose a genre for the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre of the book'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Language of the book'),
        ),
    ]
