# Generated by Django 4.0.4 on 2022-04-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Choose the author of the book', to='catalog.author', verbose_name='The author of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose a genre for the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='The genre of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='No longer than 13 symbols', max_length=13, verbose_name='The ISBN of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='The language of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Input the name of the book', max_length=200, verbose_name='The name of the book'),
        ),
    ]
